<a style="cursor: pointer;" onclick="emoticon(':D')"><img src="images/smilies/biggrin.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':(')"><img src="images/smilies/sad.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':shock:')"><img src="images/smilies/eek.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':P')"><img src="images/smilies/razz.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':oops:')"><img src="images/smilies/redface.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':evil:')"><img src="images/smilies/evil.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':roll:')"><img src="images/smilies/rolleyes.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(';)')"><img src="images/smilies/wink.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':!:')"><img src="images/smilies/exclaim.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':?:')"><img src="images/smilies/question.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':idea:')"><img src="images/smilies/idea.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':arrow:')"><img src="images/smilies/arrow.gif" border="0"></a>&nbsp;
<a style="cursor: pointer;" onclick="emoticon(':|')"><img src="images/smilies/neutral.gif" border="0"></a>